<a href="https://colab.research.google.com/github/saifmukadam10/Broadcasting_in_python/blob/main/Broadcasting_In_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
a = np.array([[56.23, 0.0, 4.4, 68.00],[1.2, 104.00, 58.00, 8.8], [1.8,135.5, 99.0, 9.9]])
print(a)

[[ 56.23   0.     4.4   68.  ]
 [  1.2  104.    58.     8.8 ]
 [  1.8  135.5   99.     9.9 ]]


In [4]:
cal = a.sum(axis=0)
print (cal)

[ 59.23 239.5  161.4   86.7 ]


In [5]:
percentage = 100*a/cal.reshape(1,4)
print(percentage)

[[94.93499916  0.          2.72614622 78.43137255]
 [ 2.02600034 43.42379958 35.93556382 10.14994233]
 [ 3.03900051 56.57620042 61.33828996 11.41868512]]
